version: '3.8'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - documenso-network

  inbucket:
    image: inbucket/inbucket
    ports:
      - '9000:9000' # Assuming you need the web interface accessible
    networks:
      - documenso-network

  documenso:
    image: documenso:latest # Update this with your actual image name
    build: .
    depends_on:
      - database
      - inbucket
    environment:
      NEXT_PRIVATE_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      NEXT_PRIVATE_DIRECT_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      NEXT_PUBLIC_WEBAPP_URL: ${NEXT_PUBLIC_WEBAPP_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SMTP_MAIL_HOST: inbucket
      SMTP_MAIL_PORT: 2500
      SMTP_MAIL_USER: ${SMTP_MAIL_USER}
      SMTP_MAIL_PASSWORD: ${SMTP_MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
    ports:
      - '3000:3000' # Expose if necessary for local development or external access
    volumes:
      - documenso-app:/app
    networks:
      - documenso-network

networks:
  documenso-network:
    driver: bridge

volumes:
  documenso-app:
    name: documenso-app-volume
